### ISSUE TITLE
Interoperability and extensibility section

### ISSUE THREAD

**Issue by jarrodmillman** [BIDS-numpy/numpy-paper#39]
This section needs to be revised.  It includes text from Sebastian's draft of the old "Array function protocol" section, text I copied and pasted from NEP 18, a version of Sebastian's text on dtypes as rewritten/revised by Stefan.  It also has a draft figure that Stefan made.

Possibly, the title (and content) of this section could be something like "Interoperability, extensibility, and evolvability".  But I want it to include (at least in some general sense) some sense of what is going on in NEP 16, 18, 22, 30, 33, and 37 (maybe I missed one or two).  Rather than explain any particular NEP of implementation detail, the idea is to capture the general problem we are working on with some sense of the work that has been done, (perhaps how well that has been received by the community), and what type of things are ongoing.

It also needs to flow from the changing computational landscape section, which is the bridge between "classic NumPy" (i.e., the NumPy arrays section) and "new NumPy" (i.e., the Interoperability and extensibility section).  My initial plan is for the changing computational landscape section to not include( many, if any,) explicit references to specific packages, while this section will make several explicit mentions.

We are **not** including code snippets, explicit references to NEPS, or NumPy version numbers.  Those things can be in the methods section.

Some things to consider while working on the revision:

- does the draft figure help?  do things need to be added or removed from it?
- text and figure need to be better integrated
- figure caption needs to be revised (the figure and caption shouldn't require reading the text to make sense; similarly the text should stand on its own, but the figure should clarify what is in the main body of the text)
- do we explicitly use "duck array" / "duck typing"?  if so, we need to explain them.  (personally I like the term, but am fine if we remove it)
- are we missing any thing?  e.g.,  compressed arrays (as in blosc), alternative formats such as Arrow

Thoughts?  Suggestions?

**Comment by seberg** [comment]
I like the graphic, but it seems not really necessary. One option could be (if we have space) to move the graphic and even some of the packages list to the Methods section instead. With the idea to create a place less about NumPy but more about "tools beyond NumPy" that readers may be interested in.
