### ISSUE TITLE
The proliferation of arrays section

### ISSUE THREAD

**Issue by jarrodmillman** [BIDS-numpy/numpy-paper#40]
@rgommers is tentatively planning to work on this over the weekend.  It will need to bridge between "classic NumPy" (i.e., the NumPy arrays section) and "new NumPy" (i.e., the Interoperability and extensibility section). My initial plan is for the "Changing computational landscape" section to not include (many, if any,) explicit references to specific packages, while the "Interoperability and extensibility" section will make several explicit mentions.  That may change, but we just want to make sure that we don't explain or reference packages multiple times. 

We are not including code snippets, explicit references to NEPS, or NumPy version numbers. Those things can be in the methods section.

I added some comments directly in the text, but I am adding this issue so that other people can easily add suggestions or thoughts about what should be in the section.

Thoughts?

**Comment by rgommers** [comment]
I thought about adding a figure like:

![image](https://user-images.githubusercontent.com/98330/72287057-a9a51380-3646-11ea-89b5-55e0335a4611.png)

but on second thought that's probably better left out. Especially because the editorial policies will not allow using logos in that timeline (we had that happen for SciPy)

**Comment by jarrodmillman** [comment]
@rgommers  I agree that we probably don't want to add the figure, but this section should basically flesh this picture out in narrative form.  I removed pandas from the ecosystem section, since I think it belongs in this section.  Maybe the proliferation section should start by pointing out the limitation of the ecosystem built on just NumPy.  In particular, describing the usefulness of labelled arrays / dataframes for statistical and financial work and how pandas addresses that need and interacts with NumPy.  It would be nice to see some mention of numba and xarray after that.  Then dask and finally the tensor libraries.

You may need to modify the last paragraph of the ecosystem section, which is meant to motivate/set up the proliferation section.  You may also need to lightly rework some of the interoperability section to make things flow well, but I am less certain that will be a problem.

**Comment by rgommers** [comment]
That sounds like a good plan. 

Xarray needs to come right after Pandas. Numba less sure; if we add it we should also add Cython and Pythran (and perhaps PyPy).

**Comment by jarrodmillman** [comment]
@rgommers Stefan and I made more progress on the ecosystem section.  It still needs work, but you should be able to see where we are going.  We will finish working on this section later this week.

I have some notes commented out at the top of the proliferation section mentioning some topics you may want to address.  I am also not particularly wed to any of the words (i.e., not comments) in that section, so feel free to delete anything that doesn't fit.

One problem we faced in the ecosystem section was making sure it wasn't just a long list of packages.  You may have a similar issue with the proliferation section.  If you find the need to mention a laundry list of packages, you may want to use a table or something.  We also found it helpful to keep asking ourselves what a scientist (perhaps one that doesn't program much if any) likely to be interested in.  Of course, we will also have technical readers so we want to provide some details for them as well.

I agree Numba/Cythn/Pythran/PyPy belong together and am also not sure they belong in this paper.  Unless you feel compelled to, I would leave them out for now.

**Comment by rgommers** [comment]
Agree with leaving accelerators out. Or put them in Discussion if that makes sense; they're more of a topic for the future.
