### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by jarrodmillman** [BIDS-numpy/numpy-paper#41]
Stefan has added several hand drawn figures.  The plan is to eventually turn them into polished graphics.  But for now we would like feedback.

Thoughts?

**Comment by seberg** [comment]
I like them. Just nitpicks right now: for "fancy indexinig" I prefer "advanced indexing" personally. I wonder how advanced the advanced indexing should be, although together with broadcasting it seems clear and understandable.

The reduction figure could include `axis=(0, 1)` maybe.

**Comment by stefanv** [comment]
Good idea, the `axis=(0, 1)` would be easy to add, I think.

**Comment by rgommers** [comment]
Isn't figure 2 duplicate with the indexing/broadcasting sections of figure 1?

**Comment by rgommers** [comment]
Oh wait, it changed over the weekend, never mind my duplication comment.
