### ISSUE TITLE
Consider referring to Astropy / Astropy award

### ISSUE THREAD

**Issue by matthew-brett** [BIDS-numpy/numpy-paper#42]
Astropy just won a Royal Astronomy Society Group award <https://ras.ac.uk/news-and-press/news/leading-astronomers-and-geophysicists-honoured-ras-bicentenary-year-0>.

Full text at <https://ras.ac.uk/sites/default/files/2020-01/Group%20Award%20-%20Astropy.pdf>

This includes:

> A committee of four (Tom Aldcroft, Thomas Robitaille, Kelle Cruz and Erik Tollerud) coordinated the mostly unfunded development of over 200,000 lines of high-quality program code by a team of nearly 250 individual developers; the committee is the public face of Astropy and they ensure consensus amongst the developers and compliance with community standards.
The Astropy Project has provided hundreds of junior scientists with experience in professional-standard software development practices including use of version control, unit testing, code review and issue tracking procedures. This is a vital skillset for modern researchers that is often missing from formal university education in physics or astronomy.

**Comment by jarrodmillman** [comment]
Done.  See Discussion.
