### ISSUE TITLE
Discussion of social / cultural factors in success of open source

### ISSUE THREAD

**Issue by matthew-brett** [BIDS-numpy/numpy-paper#47]
https://paulromer.net/jupyter-mathematica-and-the-future-of-the-research-paper/

Discussion of Mathematica / Jupyter; substantial, by an economist.

**Comment by rgommers** [comment]
That does come at a time when the values of open source are, justifiably, questioned more and more. E.g. https://dev.to/degoodmanwilson/open-source-is-broken-g60

It's a decent blog post and Paul Romer is a famous scientist, but it also comes from a fairly naive, "I'm new to all this" point of view.

**Comment by seberg** [comment]
I honestly think that those two things go into completely different (non-exclusive) points. One is about the *value* of open source, the other is about the *ethical values/ideals* of open source possibly being  misaligned at times.

**Comment by matthew-brett** [comment]
Yes, I agree the two articles are making different points. I found Romer's article much more convincing than Goodman-Wilson's; I didn't find Romer's article to be naive myself.
