### ISSUE TITLE
Reach out to all potential co-authors

### ISSUE THREAD

**Issue by stefanv** [BIDS-numpy/numpy-paper#68]
We have not been able to reach all of the co-authors listed on the paper via email.  If you get this notification, please respond to this issue to confirm whether you want to be on the paper.

@pv
@rkern
@juliantaylor
@jaimefrio
@mwiebe
@dmcooke

and Pierre Gerard-Marchant, for whom we cannot find a GitHub handle.

If anyone else knows how to contact these people, please let us know.

**Comment by rkern** [comment]
Yes, please!

**Comment by seberg** [comment]
I think it is @pierregm. For immediate context: this is about inclusion as an author in a new NumPy paper.

**Comment by jarrodmillman** [comment]
Pauli and Julian have responded (positively) via email.  We are still waiting to hear from Jaime, Mark, David, and Pierre.

**Comment by jarrodmillman** [comment]
Pierre has responded (positively) via email. We are still waiting to hear from Jaime, Mark, and David.

**Comment by jarrodmillman** [comment]
Jaime and Mark have responded (positively) via email.  We still haven't heard from David.
