### ISSUE TITLE
Review protocols paragraph in "Array proliferation and interoperability"

### ISSUE THREAD

**Issue by stefanv** [BIDS-numpy/numpy-paper#69]
https://github.com/BIDS-numpy/numpy-paper/blob/d94a154fae8a93daf866c5af692e304fbc3ea3de/body.tex#L380

> To facilitate this \emph{interoperability}, NumPy provides
``protocols'' (or contracts of operation), that allow for specialized arrays to be
passed to NumPy functions (Fig.~\ref{fig:array-protocol}).
NumPy, in turn, dispatches operations to the originating library, as required.
Over three hundred of the most popular
NumPy functions are supported.  The protocols are implemented by at
least five libraries, including Dask, CuPy, xarray, and PyData/Sparse.
Thanks to these developments, users can now, for example, scale
their computation from a single machine to distributed systems using Dask.
The protocols \textit{compose} well, and so it is possible to redeploy NumPy
code onto multi-GPU systems with minimal changes\cite{entschev2019}.
Working with the community, we have identified several issues that
prevent further adoption, and are refining interfaces to reduce
impedance mismatch.

@shoyer @rgommers @seberg

**Comment by seberg** [comment]
Reads ~pretty nice~ great :), I think the 300+ number comes from `__array_function__`, we should add all ufuncs, which adds:
```
ufuncs = {sym for sym in np.__dict__.values() if isinstance(sym, np.ufunc)}
print(len(ufuncs))  # 86
```
On top of the 316 which @shoyer listed here: https://github.com/numpy/numpy/issues/15544#issuecomment-584453408 making it just over 400.

**Comment by rgommers** [comment]
>  The protocols are implemented by at least five libraries, including Dask, CuPy, xarray, and PyData/Sparse.

It's slightly odd to say "at least 5" and then list 4 of those 5. What's the 5th one?

How about simply _"The protocols are implemented by widely used libraries like Dask, CuPy, xarray, and PyData/Sparse."_?

> Working with the community, we have identified several issues that prevent further adoption, and are refining interfaces to reduce impedance mismatch.

I don't think this is quite true, nor is it clear yet that the new `__array_module__` proposal is better in all respects (new limitations were just uncovered on the mailing list). Also, PyTorch is still planning to adopt the protocol, it's just a lot of work to prepare for it (NumPy compat needs to be improved). 

I would either leave this sentence out or change it to a more positively phrased sentence like _"We plan to introduce one more protocol to expand coverage to more NumPy functions, in particular those that create new arrays."_

**Comment by jarrodmillman** [comment]
> To facilitate this \emph{interoperability}, NumPy provides
``protocols'' (or contracts of operation), that allow for specialized arrays to be
passed to NumPy functions (Fig.~\ref{fig:array-protocol}).
NumPy, in turn, dispatches operations to the originating library, as required.
Over four hundred of the most popular NumPy functions are supported.
The protocols are implemented by widely used libraries such as Dask, CuPy,
xarray, and PyData/Sparse.
Thanks to these developments, users can now, for example, scale
their computation from a single machine to distributed systems using Dask.
The protocols also \textit{compose} well, allowing users to redeploy NumPy
code at scale on distributed, multi-GPU systems via, for instance, CuPy arrays embedded in Dask
arrays. Using NumPy's high-level API, users can leverage highly parallel code
execution on multiple systems with millions of cores, all with minimal code
changes \cite{entschev2019}.

> These array protocols are now a key feature of NumPy, and are expected to only
increase in importance.  As with the rest of NumPy, we iteratively refine and
add protocol designs to improve utility and simplify adoption.

**Comment by rgommers** [comment]
LGTM!

**Comment by rgommers** [comment]
I think we can call this good, closing.
