### ISSUE TITLE
Add more background on linear algebra libraries

### ISSUE THREAD

**Issue by jarrodmillman** [BIDS-numpy/numpy-paper#72]
We were asked to add more background on linear algebra libraries to 
https://github.com/BIDS-numpy/numpy-paper/blob/275ccea0f5913e98fba3f580a8f6b2680b3e0acf/methods.tex#L67

This will probably be a few sentences to a paragraph.

Here is what was specifically requested:
> [C]larify that for certain core functions, in particular in linear algebra, that NumPy provides an interface to other software projects with an even longer history (e.g. EISPACK and LINPACK, which grew into LAPACK and the BLAS, and various sparse matrix packages). This is alluded to, by saying that NumPy depends on OpenBLAS for accelerated linear algebra (p. 3), and similar statements on p. 10 and elsewhere. But I think it might be worth pointing out more strongly that doing linear algebra correctly is a huge and extremely well developed field, and that the underlying linear algebra software itself codifies an impressive collection of expertise that is to a large extent distinct from the NumPy development community. By this I do not mean to criticize the NumPy team (many of whom have a very good understanding of numerical linear algebra) or suggest that they are trying to take too much credit. On the contrary, I think it is a very important feature of NumPy that it provides an easy-to-use interface to software developed over decades by a much broader set of experts, software that is also used in its C and Fortran versions as the standard for linear algebra, and that has the full stamp of approval from the numerical analysis community as well as a host of application communities. I think this is worth pointing out to readers who may not be aware of this, since one concern potential users have (or should have) with any "black box" solvers they use is whether they implement robust and reliable methods. So pointing this out more strongly would help to highlight an important feature of NumPy. Perhaps this could be done in the Methods section, where some of the linear algebra functions are listed on page 9.

**Comment by seberg** [comment]
Hmmm, I am thinking of including something like:
```diff
-NumPy's linear algebra library includes functions for: solving linear
+NumPy's linear algebra library provides an interface to established
+linear algebra methods for: solving linear
```
plus maybe a final sentence: "These algorithms themselves look back at a long history of research and open developement."

The "open" part seems right considering BLAS/LAPACKs open licensing?  We could cite the lapack user guide (it is already in the bibtex), but it does not have much history here. This has some nice history: https://archive.siam.org/meetings/la09/history_talks.php but not sure its very nice for citation, and goes quite far beyond the numerical implementation or modern algorithms.

**Comment by seberg** [comment]
Ah, I think this is probably a good citation:
Dongarra, Jack; Hammarling, Sven (1990). "Evolution of Numerical Software for Dense Linear Algebra". In Cox, M. G.; Hammarling, S. (eds.). Reliable Numerical Computation. Oxford: Clarendon Press. pp. 297–327. ISBN 0-19-853564-3.

**Comment by jarrodmillman** [comment]
Here is a source I used in the past:
http://history.siam.org/oralhistories/dongarra.htm

 Citation: Jack Dongarra, Oral history interview by Thomas Haigh, 26 April, 2005, University of Tennessee, Knoxville TN. Society for Industrial and Applied Mathematics, Philadelphia, PA

**Comment by seberg** [comment]
I looked at the chapter, and it looks nice to me. It has a section on EISPACK and LAPACK, etc. the "open" statement I will sign of as EISPACK, lapack and blas being all freely licensed.

**Comment by jarrodmillman** [comment]
Any update on when you plan to finish this?

**Comment by seberg** [comment]
Sorry, I can make a PR with such changes, and will think about it a bit more. Or do you think it should be longer and mention a bit history, e.g. Lapack?

**Comment by jarrodmillman** [comment]
If you have time, some Lapack history would be nice to include.  We have plenty of space left to expand.  Stefan and I are pretty much ready to resubmit as soon as we incorporate this and the PRG addition.
