### ISSUE TITLE
Add more background on PRGs

### ISSUE THREAD

**Issue by jarrodmillman** [BIDS-numpy/numpy-paper#73]
We were asked to add more background on PRGs to
https://github.com/BIDS-numpy/numpy-paper/blob/275ccea0f5913e98fba3f580a8f6b2680b3e0acf/methods.tex#L349
This will probably be a few sentences at most.

Here is what was specifically requested:
> Proper generation of pseudo-random numbers has been the subject of intense study for decades and there are many horror stories regarding the use of badly generated random numbers in various contexts. Developing software to generate them properly requires a deep understanding of number theory and statistics. The "Random number generation" section starting on p. 11 primarily discusses the API, with some references to various other random number packages. A reader like myself, who doesn't know this field well, might like to see a similar reassurance that NumPy is using the best state-of-the-art software under the hood in this domain. Presumably it is, but a statement of this with perhaps some references to the relevant literature might be worth adding.

> Again, nobody should expect the developers of NumPy to be experts in the mathematics and algorithm development for all the things supported in NumPy, and it is a major contribution to the community that these aspects of NumPy can be confidently used as a black box because of its incorporation of the best available software. It is also perhaps worth mentioning that this would be impossible if not for the fact that significant portions of these other communities made a commitment to open source software long ago, so that the core functionality of NumPy can also be entirely open source.

**Comment by jarrodmillman** [comment]
@bashtage Any suggestions?   A sentence may suffice.

**Comment by bashtage** [comment]
I'll update it tomorrow. There is an active issue on NumPy with some controversy about the default PRNG, so I was hoping to wade through that to avoid pitfalls. (Trying not to link to avoid spill over)

**Comment by jarrodmillman** [comment]
@bashtage Any update on when you plan to finish this?

**Comment by bashtage** [comment]
@jarrodmillman Just added a PR with some background.
